// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TabletopStats.Infrastructure;

#nullable disable

namespace TabletopStats.Infrastructure.Migrations
{
    [DbContext(typeof(RpgContext))]
    [Migration("20251111144057_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TabletopStats.Infrastructure.Entity.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SessionInfoSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SessionInfoSessionId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("TabletopStats.Infrastructure.Entity.RpgSystem", b =>
                {
                    b.Property<Guid>("SystemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SystemId");

                    b.ToTable("RpgSystems");
                });

            modelBuilder.Entity("TabletopStats.Infrastructure.Entity.SessionInfo", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GameMasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RpgSystemSystemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SessionId");

                    b.HasIndex("GameMasterId");

                    b.HasIndex("RpgSystemSystemId");

                    b.ToTable("SessionInfos");
                });

            modelBuilder.Entity("TabletopStats.Infrastructure.Entity.Person", b =>
                {
                    b.HasOne("TabletopStats.Infrastructure.Entity.SessionInfo", null)
                        .WithMany("Players")
                        .HasForeignKey("SessionInfoSessionId");
                });

            modelBuilder.Entity("TabletopStats.Infrastructure.Entity.SessionInfo", b =>
                {
                    b.HasOne("TabletopStats.Infrastructure.Entity.Person", "GameMaster")
                        .WithMany()
                        .HasForeignKey("GameMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TabletopStats.Infrastructure.Entity.RpgSystem", "RpgSystem")
                        .WithMany()
                        .HasForeignKey("RpgSystemSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameMaster");

                    b.Navigation("RpgSystem");
                });

            modelBuilder.Entity("TabletopStats.Infrastructure.Entity.SessionInfo", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
