// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TabletopStats.Infrastructure;

#nullable disable

namespace TabletopStats.Infrastructure.Migrations
{
    [DbContext(typeof(RpgContext))]
    [Migration("20251112210128_UpdateAdventureCampaingRelation")]
    partial class UpdateAdventureCampaingRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonSessionLog", b =>
                {
                    b.Property<Guid>("PlayersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SessionPlayedSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlayersId", "SessionPlayedSessionId");

                    b.HasIndex("SessionPlayedSessionId");

                    b.ToTable("PlayerSessionLog", (string)null);
                });

            modelBuilder.Entity("TabletopStats.Domain.Entities.Adventure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Adventures");
                });

            modelBuilder.Entity("TabletopStats.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("TabletopStats.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("TabletopStats.Domain.Entities.RpgSystem", b =>
                {
                    b.Property<Guid>("SystemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SystemId");

                    b.ToTable("RpgSystems");
                });

            modelBuilder.Entity("TabletopStats.Domain.Entities.SessionLog", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdventureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GameMasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RpgSystemSystemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SessionId");

                    b.HasIndex("AdventureId");

                    b.HasIndex("GameMasterId");

                    b.HasIndex("RpgSystemSystemId");

                    b.ToTable("SessionLogs", (string)null);
                });

            modelBuilder.Entity("PersonSessionLog", b =>
                {
                    b.HasOne("TabletopStats.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PlayersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TabletopStats.Domain.Entities.SessionLog", null)
                        .WithMany()
                        .HasForeignKey("SessionPlayedSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TabletopStats.Domain.Entities.Adventure", b =>
                {
                    b.HasOne("TabletopStats.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Adventures")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("TabletopStats.Domain.Entities.SessionLog", b =>
                {
                    b.HasOne("TabletopStats.Domain.Entities.Adventure", "Adventure")
                        .WithMany("Sessions")
                        .HasForeignKey("AdventureId");

                    b.HasOne("TabletopStats.Domain.Entities.Person", "GameMaster")
                        .WithMany("SessionRan")
                        .HasForeignKey("GameMasterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TabletopStats.Domain.Entities.RpgSystem", "RpgSystem")
                        .WithMany()
                        .HasForeignKey("RpgSystemSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adventure");

                    b.Navigation("GameMaster");

                    b.Navigation("RpgSystem");
                });

            modelBuilder.Entity("TabletopStats.Domain.Entities.Adventure", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("TabletopStats.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("Adventures");
                });

            modelBuilder.Entity("TabletopStats.Domain.Entities.Person", b =>
                {
                    b.Navigation("SessionRan");
                });
#pragma warning restore 612, 618
        }
    }
}
