// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TabletopStats.Infrastructure;

#nullable disable

namespace TabletopStats.Infrastructure.Migrations
{
    [DbContext(typeof(RpgContext))]
    partial class RpgContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonSessionLog", b =>
                {
                    b.Property<Guid>("PlayersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SessionPlayedSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlayersId", "SessionPlayedSessionId");

                    b.HasIndex("SessionPlayedSessionId");

                    b.ToTable("PlayerSessionLog", (string)null);
                });

            modelBuilder.Entity("TabletopStats.Infrastructure.Entity.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("TabletopStats.Infrastructure.Entity.RpgSystem", b =>
                {
                    b.Property<Guid>("SystemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SystemId");

                    b.ToTable("RpgSystems");
                });

            modelBuilder.Entity("TabletopStats.Infrastructure.Entity.SessionLog", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GameMasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RpgSystemSystemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SessionId");

                    b.HasIndex("GameMasterId");

                    b.HasIndex("RpgSystemSystemId");

                    b.ToTable("SessionLogs", (string)null);
                });

            modelBuilder.Entity("PersonSessionLog", b =>
                {
                    b.HasOne("TabletopStats.Infrastructure.Entity.Person", null)
                        .WithMany()
                        .HasForeignKey("PlayersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TabletopStats.Infrastructure.Entity.SessionLog", null)
                        .WithMany()
                        .HasForeignKey("SessionPlayedSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TabletopStats.Infrastructure.Entity.SessionLog", b =>
                {
                    b.HasOne("TabletopStats.Infrastructure.Entity.Person", "GameMaster")
                        .WithMany("SessionRan")
                        .HasForeignKey("GameMasterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TabletopStats.Infrastructure.Entity.RpgSystem", "RpgSystem")
                        .WithMany()
                        .HasForeignKey("RpgSystemSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameMaster");

                    b.Navigation("RpgSystem");
                });

            modelBuilder.Entity("TabletopStats.Infrastructure.Entity.Person", b =>
                {
                    b.Navigation("SessionRan");
                });
#pragma warning restore 612, 618
        }
    }
}
